import { DatabaseSync } from 'node:sqlite';
import { createHash } from 'node:crypto';
import { applySourceDeltaLocal } from './local_v2_updater_core.mjs';
const p='/mnt/data/GIL_SQLITE_UPDATER_CORE_TEST.db';
const db=new DatabaseSync(p);
const src=db.prepare("select source_id from v2_source_objects where sosl_code='TESTV2I01'").get();
const rev=db.prepare('select last_processed_revision from v2_sync_state where source_id=?').get(src.source_id).last_processed_revision;
const rows=db.prepare(`select stable_ref,unit_type,position_ordinal,heading_path,content_text,content_hash,provenance_locator from v2_content_units where source_id=? and active=1 order by position_ordinal,content_pk`).all(src.source_id);
db.close();
const desired=rows.map(r=>({...r}));
const target=desired.find(x=>x.stable_ref==='TESTV2I01:section:004');
target.content_text='UNIDADE: ALFA — LOCAL SQLITE DELTA PROBE';
target.content_hash=createHash('sha256').update(target.content_text).digest('hex');
const removeIndex=desired.findIndex(x=>x.stable_ref==='TESTV2I01:section:005');
desired.splice(removeIndex,1);
desired.push({stable_ref:'TESTV2I01:section:local-probe',unit_type:'paragraph',position_ordinal:999,heading_path:'LOCAL PROBE',content_text:'LOCAL SQLITE DELTA PROBE NOVA UNIDADE',provenance_locator:'probe:local'});
const sourceHash=createHash('sha256').update(JSON.stringify(desired.map(x=>[x.stable_ref,x.content_text]))).digest('hex');
const result=applySourceDeltaLocal({dbPath:p,code:'TESTV2I01',expectedBaselineRevision:rev,observedRevision:'drive-version:LOCAL-PROBE-21',sourceHash,desiredUnits:desired});
console.log(JSON.stringify(result,null,2));
